spring:
  datasource:
    url: jdbc:postgresql:andudb
    username: postgres
    password: tough-pwd-pg
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
